#include "defs.h"


#define IOCTL_BLACKBONE_GRANT_ACCESS   (ULONG)CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

NTSTATUS BBDispatch(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
